# Generated by Django 6.0.3 on 2026-09-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notifications_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
