# Generated by Django 6.0.3 on 2026-09-16 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('original_check_in', models.DateTimeField(blank=True, null=True)),
                ('original_check_out', models.DateTimeField(blank=True, null=True)),
                ('effective_check_in', models.DateTimeField(blank=True, null=True)),
                ('effective_check_out', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('source', models.CharField(choices=[('browser', 'Chấm công trên web'), ('correction', 'Sửa chấm công'), ('hr_historical', 'HR ghi bổ sung')], default='browser', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='unique_attendance_per_day')],
            },
        ),
    ]
